#single container pod
kind: Pod
apiVersion: v1
metadata:
  name: singlepod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo hello world; sleep 10; done"]
